import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import Header from "@/components/Header";
import LeftBar from "@/components/LeftBar";
import BottomLeftBar from "@/components/bottomLeftBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="flex flex-row ">
            <LeftBar className="sticky top-0 bg-white px-3 w-fit flex flex-col min-h-screen justify-between overflow-auto left-0 max-md:hidden " />
            <section className="flex min-h-screen flex-1 flex-col items-center bg-dark-1 px-6 pb-10 max-md:w-full max-md:p-0 ">
              <div className="w-full h-full">{children}</div>
            </section>
            <BottomLeftBar className="fixed bottom-0 z-10 w-full rounded-t-3xl bg-glassmorphism p-4 backdrop-blur-lg xs:px-7 md:hidden" />
          </main>
        </body>
      </html>
    </AuthProvider>
  );
}
